import { SessionManager } from "../session/session-manager";
import type {
  ModelProvider,
  ModelRequest,
  ModelResponse,
} from "../provider/provider.interface";

interface DispatchedCall {
  sessionId?: string;
  model?: string;
  prompt: string;
  timestamp: number;
}

class ModelTrackingProvider implements ModelProvider {
  readonly name = "model_tracking_provider";
  readonly defaultModel = "default/fallback-model";
  readonly dispatchedCalls: DispatchedCall[] = [];

  async complete(request: ModelRequest): Promise<ModelResponse> {
    const lastMsg = request.messages[request.messages.length - 1];
    const prompt = lastMsg?.content || "";

    const call: DispatchedCall = {
      sessionId: request.sessionId,
      model: request.model,
      prompt,
      timestamp: Date.now(),
    };
    this.dispatchedCalls.push(call);

    return {
      thought: `Executing prompt with assigned model strategy: ${request.model}`,
      content: `[Response generated by ${request.model}]: Sandboxing isolates process execution within kernel cgroups and namespaces.`,
      finishReason: "stop",
    };
  }
}

export async function runModelSelectionVerification() {
  console.log(
    "================================================================================",
  );
  console.log(
    "CRUCIBLE VERIFICATION: PER-SESSION MODEL SELECTION & DISPATCH LOGGING",
  );
  console.log(
    "================================================================================\n",
  );

  const provider = new ModelTrackingProvider();
  const manager = new SessionManager({
    defaultModel: "default/fallback-model",
    defaultProvider: provider,
  });

  const promptText = "Write a one-line explanation of sandboxed execution";

  // 1. Create Session 1 with Anthropic Claude 3.5 Sonnet
  const model1 = "anthropic/claude-3.5-sonnet";
  const session1 = await manager.createSession({
    title: "Claude Architecture Session",
    model: model1,
  });
  console.log(`[Session 1 Created] ID: ${session1.id}`);
  console.log(`  -> Selected Model: ${session1.getModel()}`);

  // 2. Create Session 2 with Meta Llama 3.3 70B Instruct
  const model2 = "meta-llama/llama-3.3-70b-instruct";
  const session2 = await manager.createSession({
    title: "Llama Fast Execution Session",
    model: model2,
  });
  console.log(`[Session 2 Created] ID: ${session2.id}`);
  console.log(`  -> Selected Model: ${session2.getModel()}\n`);

  // 3. Send the exact same prompt to both sessions
  console.log(
    `[Prompt Dispatch] Sending same prompt to both sessions: "${promptText}"\n`,
  );
  const res1 = await session1.prompt(promptText);
  const res2 = await session2.prompt(promptText);

  // 4. Verify dispatched model tag per request
  const call1 = provider.dispatchedCalls.find(
    (c) => c.sessionId === session1.id,
  );
  const call2 = provider.dispatchedCalls.find(
    (c) => c.sessionId === session2.id,
  );

  console.log("--- DISPATCH LOG VERIFICATION ---");
  console.log(`Session 1 (${session1.id}):`);
  console.log(`  -> Configured Model:  "${model1}"`);
  console.log(`  -> Dispatched Model:  "${call1?.model}"`);
  console.log(
    `  -> Model Tag Logged:  [model=${call1?.model}] (Strict Match: ${call1?.model === model1})`,
  );
  console.log(`  -> Response Content:  "${res1.finalResponse}"\n`);

  console.log(`Session 2 (${session2.id}):`);
  console.log(`  -> Configured Model:  "${model2}"`);
  console.log(`  -> Dispatched Model:  "${call2?.model}"`);
  console.log(
    `  -> Model Tag Logged:  [model=${call2?.model}] (Strict Match: ${call2?.model === model2})`,
  );
  console.log(`  -> Response Content:  "${res2.finalResponse}"\n`);

  // Verify non-fallback assertion
  if (
    call1?.model === "default/fallback-model" ||
    call2?.model === "default/fallback-model"
  ) {
    throw new Error(
      "FAIL: One of the sessions erroneously fell back to the default model!",
    );
  }

  if (call1?.model !== model1 || call2?.model !== model2) {
    throw new Error(
      "FAIL: Dispatched model tag does not match the session's selected model!",
    );
  }

  console.log(
    "================================================================================",
  );
  console.log(
    "PER-SESSION MODEL SELECTION VERIFIED (0 FAILURES, NO FALLBACK TO DEFAULT)",
  );
  console.log(
    "================================================================================",
  );

  manager.clear();
  process.exit(0);
}

if (import.meta.main) {
  runModelSelectionVerification().catch((err) => {
    console.error("Model selection verification failed:", err);
    process.exit(1);
  });
}
