[workspace]
resolver = "3"
members = [
    "crates/executor-core",
    "crates/ipc-proto",
    "crates/executor-grpc",
    "crates/sandbox",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Akash Kumar Sinha"]

[workspace.dependencies]
thiserror = "2.0"
tokio = { version = "1.43", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
tonic = { version = "0.12", features = ["prost"] }
tonic-health = "0.12"
tonic-build = { version = "0.12", features = ["prost"] }
prost = "0.13"
prost-types = "0.13"
executor-core = { path = "crates/executor-core" }
ipc-proto = { path = "crates/ipc-proto" }
crucible-sandbox = { path = "crates/sandbox" }
