[package]
name = "ipc-proto"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Generated Protocol Buffers and gRPC contracts for Crucible"

[dependencies]
prost.workspace = true
prost-types.workspace = true
tonic.workspace = true

[build-dependencies]
tonic-build.workspace = true
