apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crucible-staging

bases:
  - ../../base

resources:
  - ../../policies/resource-quota.yaml
  - ../../policies/network-policy.yaml
  - ../../policies/autoscaling.yaml
  - ../../policies/karpenter-nodepool.yaml

patchesStrategicMerge:
  - patch-staging.yaml

generatorOptions:
  disableNameSuffixHash: true
