apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crucible

commonLabels:
  app.kubernetes.io/part-of: crucible

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - executor-grpc-deployment.yaml
  - orchestrator-deployment.yaml
  - executor-job-template.yaml
  - web-deployment.yaml
  - livekit-deployment.yaml
  - ingress.yaml
